const COLOR_RED = "#F00";           // Rosso
const COLOR_GREEN = "#0F0";         // Verde
const COLOR_BLUE = "#00F";          // Blu
const COLOR_YELLOW = "#FF0";        // Giallo
const COLOR_CYAN = "#0FF";          // Ciano
const COLOR_MAGENTA = "#F0F";       // Magenta
const COLOR_BLACK = "#000";         // Nero
const COLOR_WHITE = "#FFF";         // Bianco
const COLOR_GRAY = "#808080";       // Grigio
const COLOR_SILVER = "#C0C0C0";     // Argento
const COLOR_LIGHT_BROWN = "#800000";      // Marrone
const COLOR_OLIVE = "#808000";      // Oliva
const COLOR_PURPLE = "#800080";     // Viola
const COLOR_TEAL = "#008080";       // Verde acqua
const COLOR_NAVY = "#000080";       // Blu scuro
const COLOR_LIME = "#00FF00";       // Limetta
const COLOR_AQUA = "#00FFFF";      // Acquamarina
const COLOR_FUCHSIA = "#FF00FF";   // Fucsia
const COLOR_ORANGE = "#FFA500";     // Arancione
const COLOR_PINK = "#FFC0CB";       // Rosa
const COLOR_BROWN = "#A52A2A";      // Marrone chiaro
